### ISSUE TITLE
Support tags other than meta

### ISSUE THREAD

**Issue by gdub22** [ronco/ember-cli-meta-tags#11]
For example, `link`, which has some uses under the same realm of document metadata:
```html
<link rel="author" href="..."/>
<link rel="canonical" href="..."/>
```

**Comment by ronco** [comment]
@gdub22 This is a great idea.  I've tackled canonical links separately in the past but I think it would fit in well with this library.

For quick requirements I'm thinking:
 - [ ] able to construct elements
   - [ ] arbitrary element type
   - [ ] arbitrary attributes and values
 - [ ] ability to clear tags set on transition (consistent with current meta behavior)

We could add a new `headTags` property to the mixin (which meta can be updated to just be an adapter for maintaining the old api).

Clearing the tags would be the trickiest part since we'd need to determine an appropriate selector.  We could use the `id` attribute if provided.  If not given we could auto generate an id with routeName + the attribute names.  I worry about not correctly clearing, but providing the `id` selector would be reliable and I can document that in the API if users want to be sure.

Let me know what you think.

**Comment by gdub22** [comment]
@ronco Excellent. Glad you are interested in this.

Looks like the structure for defining the metadata may have to be changed to support this.
Here's one proposal:
```js
{
  type: 'link',
  attrs: {
    rel: 'canonical',
    href: model.get('slug')
  }
},
// Implied defaults (type: 'meta', no attrs hash means properties are the attrs)
{
  property: 'og:image',
  content: model.get('imageUrl'),
}
```

Clearing is tricky as you mention.  One concern is supporting fastboot, where the selector based approach would not work anyway.
I've played around with the idea of using a component that you inject into the head.  The component's template is an each loop that renders each tag.  Clearing then is only a matter of reseting the model of the component.  Thoughts?

**Comment by ronco** [comment]
Hey @gdub22,

I would **love** to have this wrapped up in a component rather than manually manipulate the dom elements with jQuery.

However I'm not sure how to inject an ember component outside of the ember-application element.  I looked into [ember-wormhole](https://github.com/yapplabs/ember-wormhole), but it requires the component to be in the same element as the ember app.  I'll play around with it.  I definitely want this library to support Fastboot.

**Comment by jpadilla** [comment]
@ronco Just proposed https://github.com/tildeio/ember-cli-fastboot/pull/49 to allow setting meta tags. If that or something similar goes through I could help update this library to support it.

I don't think this needs to be a component at all a mixin like it is now works just fine or even how `ember-cli-document-title` does it.

**Comment by ronco** [comment]
Hey @jpadilla, that PR looks great and I would greatly appreciate help in getting this library fastboot compatible.

I think in the mean time it makes sense to enhance this library's API to support arbitrary head tags, and then when your PR gets incorporated into fastboot we can get get that support fastboot compatible as well.

Thanks!

**Comment by ronco** [comment]
@gdub22 I'm starting work on supporting additional head tags.  I'm going to use the data structure you've suggested with the addition of an optional `selector` key.  That will be used for clearing tags on transition if provided.  The auto clearing really isn't essential for a pre-rendered solution, but is nice to have for development and sanity checking.

I hope to have the code and tests wrapped up in a day or so, documentation will follow.  I also hope to get it all working with Fastboot when one of @jpadilla's PRs lands.

**Comment by gdub22** [comment]
@ronco awesome!  I started to put together a proof of concept with that data structure and using the component-based approach I mentioned.  This alleviates the need for selectors and manually clearing the tags and means it also should work with fastboot.  Let me know your thoughts and if you want to combine forces: https://github.com/gdub22/ember-document-meta

**Comment by jpadilla** [comment]
@gdub22 looking great!

**Comment by ronco** [comment]
@gdub22 That component solution is excellent!  It looks like you've already proof of concepted the core functionality.  I would love to join forces on this.
